name: Compile Catalog

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compile_catalog:
    name: Compile Catalog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install tox
      - name: Compile Catalog
        run: tox
        env:
          TOXENV: compile-catalog
