name: Check Security Vulnerabilities

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  safety:
    name: safety
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python -m pip install tox
      - name: safety
        run: tox
        env:
          TOXENV: safety
